# This file is generated by androgenizer for:
# [x] NDK
# [ ] system

NDK_OUT := lib
LOCAL_PATH:=$(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE:=libcollections

LOCAL_SRC_FILES := \
	src/array.c \
	src/bheap.c \
	src/dlist.c \
	src/hash-functions.c \
	src/hash-table.c \
	src/rbtree.c \
	src/tree-map.c \
	src/variant.c \
	src/bench-mark.c \
	src/bitset.c \
	src/flat-db.c \
	src/hash-map.c \
	src/lhash-table.c \
	src/slist.c \
	src/tstring.c \
	src/vector.c \
	-I./src/ \
	-include

LOCAL_CFLAGS := \
	-std=c99 \
	-Wall \
	-O3

LOCAL_PRELINK_MODULE := false
include $(BUILD_SHARED_LIBRARY)
